name: Run Tests

on:
  push:
    branches: [main, develop] # ou qualquer branch que quiser proteger
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout o código
        uses: actions/checkout@v3

      - name: Instala o Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # ou a versão do seu projeto

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes
        run: npm test -- --watchAll=false
